import { expect, test } from '@playwright/test'

test('primary navigation keeps every scoped destination on phones', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')

  const primary = page.getByRole('navigation', { name: 'Primary' })
  await expect(primary.getByRole('link', { name: 'Battles' })).toBeVisible()
  await expect(primary.getByRole('link', { name: 'Rosters' })).toBeVisible()
  await expect(primary.getByRole('link', { name: 'Factions' })).toBeVisible()
  await expect(page.locator('header')).toHaveJSProperty(
    'scrollWidth',
    await page.locator('header').evaluate((header) => header.clientWidth),
  )
  await page.screenshot({ path: 'test-results/navigation-phone.png', fullPage: true })
})

test('a guest can enter through the roster library and browse the product', async ({ page }) => {
  await page.goto('/rosters')
  await page.getByLabel('Your name').fill('Alice')
  await page.getByRole('button', { name: 'Continue' }).click()

  await expect(page.getByRole('heading', { name: 'My rosters' })).toBeVisible()
  await expect(page.getByText('No rosters yet. Create one or bring one from another app.')).toBeVisible()
  await page.getByRole('link', { name: /Incursion/ }).click()
  await expect(page).toHaveURL('/rosters?limit=1000')
  await page.getByRole('link', { name: 'All' }).click()
  await page.screenshot({ path: 'test-results/roster-library.png', fullPage: true })
  await page.getByRole('link', { name: 'Create editable roster' }).click()
  await expect(page).toHaveURL('/rosters/new')
  await expect(page.getByRole('heading', { name: 'Create editable roster' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Faction' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true)
  const serverResponse = await page.request.get('/rosters/new')
  expect(await serverResponse.text()).toContain('Create editable roster')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true)
  await page.screenshot({ path: 'test-results/roster-editor-phone.png' })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.getByRole('link', { name: 'Back to rosters' }).click()
  await expect(page.getByRole('link', { name: 'Import roster' })).toBeVisible()
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('link', { name: 'Import roster' }).click()
  await chooser
  await expect(page).toHaveURL('/rosters/import')
  await expect(page.getByRole('heading', { name: 'Import roster' })).toBeVisible()

  await page.getByRole('link', { name: 'Battles' }).click()
  await expect(page.getByRole('heading', { name: 'My battles' })).toBeVisible()
  await expect(page.getByText('No battles yet.')).toBeVisible()
  await page.getByRole('link', { name: 'Open a battle' }).click()
  await page.getByRole('button', { name: 'Open a battle' }).click()
  await page.getByRole('link', { name: 'Battles' }).click()
  await expect(page.locator('[data-battle-shelf="Setup"]')).toBeVisible()
  await expect(page.getByText('Waiting for an opponent')).toBeVisible()
  await page.screenshot({ path: 'test-results/battle-library.png', fullPage: true })

  await page.getByRole('link', { name: 'Factions' }).click()
  await expect(page.locator('[data-shelf="Chaos"]')).toBeVisible()
  await expect(page.locator('[data-shelf="Imperium"]')).toBeVisible()
  await expect(page.locator('[data-shelf="Xenos"]')).toBeVisible()
  const necrons = page.locator('[data-shelf="Xenos"] [data-faction="Necrons"]')
  await necrons.getByRole('button', { name: 'Add Necrons to favourites' }).click()
  await expect(page.locator('[data-shelf="Favourites"] [data-faction="Necrons"]')).toBeVisible()
  await page.screenshot({ path: 'test-results/faction-index.png', fullPage: true })
  await necrons.getByRole('link').click()
  await expect(page).toHaveURL('/factions/necrons/reference')
  await expect(page.getByRole('link', { name: /Datasheets/ })).toBeVisible()
  const cryptek = page.getByText('Cryptek Conclave').locator('../..')
  await expect(cryptek).toContainText('6 stratagems · 4 enhancements')
  await expect(cryptek).toContainText('2 DP')
  await expect(cryptek).toContainText('Priority Assets')
  await page.screenshot({ path: 'test-results/faction-reference.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/faction-reference-phone.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.getByRole('link', { name: /Datasheets/ }).click()
  await expect(page).toHaveURL(/\/reference\/datasheets$/)
  await expect(page.getByLabel('Find a datasheet')).toBeVisible()
  await page.getByLabel('Find a datasheet').fill('Overlord')
  await expect(page.getByRole('link', { name: /Overlord/ }).first()).toBeVisible()
  await page.screenshot({ path: 'test-results/faction-datasheets.png', fullPage: true })
  await page
    .getByRole('link', { name: /Overlord/ })
    .first()
    .click()
  await expect(page).toHaveURL('/factions/necrons/overlord')
  await expect(page.getByRole('heading', { name: 'Overlord', exact: true })).toBeVisible()
  await expect(page.getByText('90 pts')).toBeVisible()
  await expect(page.getByRole('heading', { name: /Ranged weapons/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Melee weapons/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Abilities/ })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Overlord', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/datasheet.png', fullPage: true })
})
