import { expect, test } from '@playwright/test'
import { signUp } from './account'

test('primary navigation keeps every scoped destination on phones', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')

  await expect(page.locator('head link[rel="preload"][as="font"]')).toHaveCount(6)
  expect(await page.evaluate(() => document.fonts.check('400 16px "Barlow Semi Condensed"'))).toBe(true)
  const primary = page.getByRole('navigation', { name: 'Primary' })
  await expect(primary.getByRole('link', { name: 'Battles' })).toBeVisible()
  await expect(primary.getByRole('link', { name: 'Rosters' })).toBeVisible()
  await expect(primary.getByRole('link', { name: 'Factions' })).toBeVisible()
  await expect(primary.getByText('Rules', { exact: true })).toHaveCount(0)
  await expect(page.locator('header')).toHaveJSProperty(
    'scrollWidth',
    await page.locator('header').evaluate((header) => header.clientWidth),
  )
  await page.screenshot({ path: 'test-results/navigation-phone.png', fullPage: true })
})

test('public reference data renders without client JavaScript', async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false })
  const page = await context.newPage()

  await page.goto('/factions')
  await expect(page.locator('[data-faction="Chaos Daemons"]')).toBeVisible()
  await page.goto('/mission-packs')
  await expect(page).toHaveURL(/\/mission-packs\/.+/)
  await expect(page.getByRole('heading', { name: 'Chapter Approved 2026-2027' })).toBeVisible()

  await context.close()
})

test('server-rendered reference pages keep route-shaped payloads', async ({ request }) => {
  const factions = await (await request.get('/factions')).body()
  const missionPack = await (await request.get('/mission-packs/chapter-approved-2026-2027')).body()

  expect(factions.byteLength).toBeLessThan(250_000)
  expect(missionPack.byteLength).toBeLessThan(250_000)
})

test('faction routes keep a stable content width', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  const widths: number[] = []
  for (const path of [
    '/factions',
    '/factions/necrons',
    '/factions/necrons/datasheets',
    '/factions/necrons/datasheets/lokhust-lord',
    '/factions/necrons/detachments/cryptek-conclave',
  ]) {
    await page.goto(path)
    widths.push((await page.locator('main').boundingBox())?.width ?? 0)
  }
  expect(new Set(widths).size).toBe(1)
  expect(widths[0]).toBeGreaterThan(0)
})

test('terrain layouts show their labels and measurement guides', async ({ page }) => {
  await page.goto('/mission-matchups/chapter-approved-2026-2027/purge-the-foe/take-and-hold')
  await page.getByRole('button', { name: 'Enlarge terrain layout A: Sweeping Engagement' }).click()

  const layout = page.getByRole('dialog').locator('svg')
  expect(await layout.locator('text').allTextContents()).toEqual(expect.arrayContaining(['AB', 'OBJECTIVE']))
  expect(await layout.locator('line[marker-end]').count()).toBeGreaterThan(0)
})

test('a player can enter through the roster library and browse the product', async ({ page }) => {
  // Signed out, the library says what it is and asks for an account.
  await page.goto('/rosters')
  await expect(page.getByRole('heading', { name: 'Your rosters' })).toBeVisible()

  await signUp(page, 'Alice')
  await page.goto('/rosters')

  await expect(page.getByRole('heading', { name: 'My rosters' })).toBeVisible()
  const rendered = await page.request.get('/rosters')
  expect(await rendered.text()).toContain('My rosters')
  await expect(page.getByText('No rosters yet. Create one or bring one from another app.')).toBeVisible()
  await page.getByRole('button', { name: /Incursion/ }).click()
  await expect(page).toHaveURL('/rosters?limit=1000')
  await page.getByRole('button', { name: 'All' }).click()
  await page.screenshot({ path: 'test-results/roster-library.png', fullPage: true })
  await page.getByRole('button', { name: 'Create editable roster' }).click()
  const dialog = page.getByRole('dialog', { name: 'Create roster' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('combobox', { name: 'Access' })).toContainText('Private — only you')
  await expect(dialog.getByLabel('Tags')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/create-roster-dialog.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/create-roster-dialog-phone.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 720 })
  await expect(dialog.getByRole('button', { name: 'Create roster' })).toBeDisabled()
  await dialog.getByRole('combobox', { name: 'Faction' }).click()
  await page.getByPlaceholder('Search factions…').fill('Necr')
  await expect(page.getByRole('option', { name: 'Necrons', exact: true })).toBeVisible()
  await expect(page.getByRole('option', { name: 'Death Guard', exact: true })).toBeHidden()
  await page.screenshot({ path: 'test-results/faction-combobox.png', fullPage: true })
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await dialog.getByRole('combobox', { name: 'Faction' }).click()
  await page.getByPlaceholder('Search factions…').fill('Necr')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await page.screenshot({ path: 'test-results/faction-combobox-phone.png', fullPage: true })
  await page.setViewportSize({ width: 1600, height: 900 })
  await page.getByRole('option', { name: 'Necrons', exact: true }).click()
  await expect(dialog.getByRole('combobox', { name: 'Battle size' })).toContainText('Strike Force')
  await expect(dialog.getByText('0/3 DP used')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Create roster' })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Select Awakened Dynasty' }).click()
  await expect(dialog.getByText('3/3 DP used')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Take and Hold', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 1600, height: 640 })
  await expect.poll(() => dialog.evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  await dialog.evaluate((element) => element.scrollTo({ top: element.scrollHeight }))
  await expect(dialog.getByRole('button', { name: 'Create roster' })).toBeInViewport()
  await dialog.getByRole('combobox', { name: 'Battle size' }).click()
  await page.getByRole('option', { name: /Onslaught/ }).click()
  await dialog.getByRole('button', { name: 'Select Cryptek Conclave' }).click()
  await expect(dialog.getByRole('button', { name: 'Create roster' })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Priority Assets', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Create roster' })).toBeEnabled()
  await dialog.getByRole('button', { name: 'Remove Cryptek Conclave' }).click()
  await dialog.getByRole('combobox', { name: 'Battle size' }).click()
  await page.getByRole('option', { name: /Strike Force/ }).click()
  await dialog.getByRole('button', { name: 'Create roster' }).click()
  await expect(page).toHaveURL(/\/rosters\/.+\/edit/)
  await expect(page.getByRole('heading', { name: /Edit Necrons — Awakened Dynasty/ })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Necrons', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Awakened Dynasty', exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Faction' })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Battle size' })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Force' })).toHaveCount(0)
  await expect(page.getByText('Take and Hold', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Roster actions' }).click()
  await page.getByRole('menuitem', { name: 'Edit roster setup' }).click()
  const setup = page.getByRole('dialog', { name: 'Edit roster setup' })
  await setup.getByRole('combobox', { name: 'Battle size' }).click()
  await page.getByRole('option', { name: /Incursion/ }).click()
  await setup.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByRole('link', { name: 'Incursion' })).toBeVisible()
  await expect(page.getByLabel('Add a unit')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true)
  await page.screenshot({ path: 'test-results/roster-editor-phone.png' })
  await page.setViewportSize({ width: 1600, height: 900 })
  await page.getByRole('button', { name: 'Roster actions' }).click()
  await page.getByRole('menuitem', { name: 'Edit roster setup' }).click()
  await setup.getByRole('button', { name: 'Remove Awakened Dynasty' }).click()
  await setup.getByRole('button', { name: 'Select Cursed Legion' }).click()
  await setup.getByRole('button', { name: 'Save changes' }).click()
  await page.getByLabel('Add a unit').fill('Lokhust Destroyers')
  await page.getByRole('button', { name: 'Add Lokhust Destroyers', exact: true }).first().click()
  await page
    .getByRole('button', { name: /^Lokhust Destroyers/ })
    .first()
    .click()
  const modifiedStrength = page.getByRole('button', {
    name: 'S 7, modified from 5 by Cursed Legion',
  })
  await expect(modifiedStrength).toBeVisible()
  await modifiedStrength.hover()
  await expect(page.getByRole('tooltip')).toContainText('5 → 7')
  await expect(page.getByRole('tooltip')).toContainText('Cursed Legion')
  await page.screenshot({ path: 'test-results/contextual-datasheet-modifier.png', fullPage: true })
  await page.getByLabel('Add a unit').fill('Skorpekh Lord')
  await page.getByRole('button', { name: 'Add Skorpekh Lord', exact: true }).first().click()
  await page.getByLabel('Add a unit').fill('Immortals')
  await page.getByRole('button', { name: 'Add Immortals', exact: true }).first().click()
  await page.locator('[data-unit="Immortals"]').getByRole('button', { name: 'Immortals', exact: true }).click()
  const immortalsWeapons = page.locator('aside[aria-label="Loadout"]')
  const gauss = immortalsWeapons.getByRole('listitem').filter({ hasText: 'Gauss blaster' })
  await expect(gauss.getByText('5', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: /modified from 5 by Cursed Legion/ })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/cursed-immortals-base-strength.png', fullPage: true })
  await page.getByRole('link', { name: 'Incursion' }).click()
  await page.getByRole('button', { name: 'Import roster' }).click()
  await expect(page.getByRole('dialog', { name: 'Import roster' })).toBeVisible()
  await page.keyboard.press('Escape')

  await page.getByRole('link', { name: 'Battles' }).click()
  await expect(page.getByRole('heading', { name: 'My battles' })).toBeVisible()
  await expect(page.getByText('No battles yet.')).toBeVisible()
  await page.getByRole('button', { name: 'New battle' }).click()
  await page.getByRole('button', { name: 'Solo practice' }).click()
  await page.getByRole('button', { name: 'Create battle' }).click()
  await page.getByRole('link', { name: 'Battles' }).click()
  await expect(page.locator('[data-battle-shelf="Setup"]')).toBeVisible()
  await expect(page.getByText('Solo practice')).toBeVisible()
  await page.screenshot({ path: 'test-results/battle-library.png', fullPage: true })

  await page.getByRole('link', { name: 'Factions' }).click()
  await expect(page.locator('[data-shelf="Chaos"]')).toBeVisible()
  await expect(page.locator('[data-shelf="Imperium"]')).toBeVisible()
  await expect(page.locator('[data-shelf="Xenos"]')).toBeVisible()
  await page.goto('/factions/dark-angels')
  const darkAngelsDatasheets = page.getByRole('link', { name: /Datasheets/ })
  await expect(darkAngelsDatasheets).toContainText('16')
  await expect(page.getByText('Detachments', { exact: true }).locator('..')).toContainText('8')
  await expect(page.getByText('Gladius Task Force', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/dark-angels-faction-content.png', fullPage: true })
  await darkAngelsDatasheets.click()
  await expect(page.locator('main > header [data-faction-mark="dark-angels"]')).toBeVisible()
  await expect(page.getByRole('link', { name: /Asmodai/ })).toBeVisible()
  await expect(page.getByRole('link', { name: /Intercessor Squad/ })).toHaveCount(0)
  await page.goto('/rosters')
  await page.getByRole('button', { name: 'Create editable roster' }).click()
  const darkAngelsSetup = page.getByRole('dialog', { name: 'Create roster' })
  await darkAngelsSetup.getByRole('combobox', { name: 'Faction' }).click()
  await page.getByPlaceholder('Search factions…').fill('Dark Angels')
  await page.getByRole('option', { name: 'Dark Angels', exact: true }).click()
  await expect(darkAngelsSetup.getByRole('button', { name: 'Select Gladius Task Force' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.goto('/factions')
  const necrons = page.locator('[data-shelf="Xenos"] [data-faction="Necrons"]')
  const favouriteSaved = page.waitForResponse(
    (response) =>
      response.ok() && response.request().method() === 'POST' && Boolean(response.request().postData()?.includes('catalogueId')),
  )
  await necrons.getByRole('button', { name: 'Add Necrons to favourites' }).click()
  await favouriteSaved
  await expect(page.locator('[data-shelf="Favourites"] [data-faction]').first()).toHaveAttribute('data-faction', 'Necrons')
  await expect(page.locator('[data-shelf="Xenos"] [data-faction]').first()).toHaveAttribute('data-faction', 'Aeldari')
  const serverRenderedFavourites = await (await page.request.get('/factions')).text()
  expect(serverRenderedFavourites).toMatch(/data-shelf="Favourites"[\s\S]+data-faction="Necrons"/)
  await page.screenshot({ path: 'test-results/faction-index.png', fullPage: true })
  await page.getByRole('link', { name: 'Rosters' }).click()
  await page.getByRole('button', { name: 'Create editable roster' }).click()
  await page.getByRole('dialog', { name: 'Create roster' }).getByRole('combobox', { name: 'Faction' }).click()
  const favourites = page.getByRole('group').filter({ has: page.getByText('Favourites', { exact: true }) })
  await expect(favourites.getByRole('option').first()).toHaveText('Necrons')
  await expect(page.getByRole('option').first()).toHaveText('Necrons')
  await expect(page.getByRole('option').first().locator('[data-faction-mark]')).toBeVisible()
  await page.getByRole('option').first().click()
  await expect(
    page.getByRole('dialog', { name: 'Create roster' }).getByRole('combobox', { name: 'Faction' }).locator('[data-faction-mark]'),
  ).toBeVisible()
  await page.getByRole('dialog', { name: 'Create roster' }).getByRole('combobox', { name: 'Faction' }).click()
  await page.keyboard.press('Escape')
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: 'Factions' }).click()
  await necrons.getByRole('link').click()
  await expect(page).toHaveURL('/factions/necrons')
  await expect(page.getByRole('link', { name: /Datasheets/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Reanimation Protocols' })).toBeVisible()
  const cryptek = page.getByText('Cryptek Conclave').locator('../..')
  await expect(cryptek).toContainText('6 stratagems · 4 enhancements')
  await expect(cryptek).toContainText('2 DP')
  await expect(cryptek).toContainText('Priority Assets')
  const descriptionPages = await Promise.all(
    ['hand-of-the-dynasty', 'skyshroud-spearhead', 'the-phaerons-armoury'].map(async (detachment) =>
      (await page.request.get(`/factions/necrons/detachments/${detachment}`)).text(),
    ),
  )
  for (const contents of descriptionPages) expect(contents).not.toContain('Description unavailable')
  await page.screenshot({ path: 'test-results/faction-reference.png', fullPage: true })
  await page.goto('/factions/necrons/detachments/hand-of-the-dynasty')
  const rapidFire = page.getByRole('button', { name: '[RAPID FIRE 1]' })
  await rapidFire.hover()
  await expect(page.getByRole('tooltip')).toContainText('Rapid Fire')
  await page.getByRole('heading', { name: 'Hand of the Dynasty', exact: true }).hover()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await rapidFire.click()
  await expect(page.getByRole('tooltip')).toContainText('Rapid Fire')
  await page.getByRole('heading', { name: 'Hand of the Dynasty', exact: true }).click()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.getByRole('link', { name: 'Necrons' }).click()
  await page.getByRole('link', { name: /Cryptek Conclave/ }).click()
  await expect(page).toHaveURL('/factions/necrons/detachments/cryptek-conclave')
  await expect(page.locator('main [data-faction-mark="necrons"]')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Cryptek Conclave', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Technosorcerous Augmentations' })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Enhancements/ })).toContainText('4')
  await expect(page.getByRole('heading', { name: 'Quantum Abacus' })).toBeVisible()
  const antiMonster = page.getByRole('button', { name: '[ANTI‑MONSTER 5+]' })
  await antiMonster.hover()
  await expect(page.getByRole('tooltip')).toContainText('Anti')
  await page.getByRole('heading', { name: 'Cryptek Conclave', exact: true }).hover()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: /Stratagems/ })).toContainText('6')
  await expect(page.getByRole('heading', { name: 'Molecular Targeting' })).toBeVisible()
  await expect(
    page
      .getByRole('heading', { name: /Stratagems/ })
      .locator('..')
      .locator('article > div:last-child'),
  ).toHaveCount(6)
  await expect(page.getByText(/Tabletop Developer Consortium/)).toBeVisible()
  await expect(page.getByText(/Descriptions provided by Wahapedia/)).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Cryptek Conclave', exact: true })).toBeVisible()
  const detachmentResponse = await page.request.get('/factions/necrons/detachments/cryptek-conclave')
  expect(await detachmentResponse.text()).toContain('Technosorcerous Augmentations')
  await page.screenshot({ path: 'test-results/detachment.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/detachment-phone.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.getByRole('link', { name: 'Necrons' }).click()
  await page.getByRole('link', { name: /Datasheets/ }).click()
  await expect(page).toHaveURL(/\/datasheets$/)
  await expect(page.getByLabel('Find a datasheet')).toBeVisible()
  await page.getByLabel('Find a datasheet').fill('Overlord')
  await expect(page.getByRole('link', { name: /Overlord/ }).first()).toBeVisible()
  await page.screenshot({ path: 'test-results/faction-datasheets.png', fullPage: true })
  await page
    .getByRole('link', { name: /Overlord/ })
    .first()
    .click()
  await expect(page).toHaveURL('/factions/necrons/datasheets/overlord')
  await expect(page.getByRole('heading', { name: 'Overlord', exact: true })).toBeVisible()
  await expect(page.getByText('90 pts')).toBeVisible()
  await expect(page.getByRole('heading', { name: /Ranged weapons/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Melee weapons/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Core abilities/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Faction abilities/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Datasheet abilities/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Reanimation Protocols' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'My Will Be Done' })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Wargear abilities/ })).toBeVisible()
  await page.getByRole('button', { name: 'Devastating Wounds' }).first().hover()
  await expect(page.getByRole('tooltip').getByText('Devastating Wounds', { exact: true })).toBeVisible()
  await expect(page.getByRole('tooltip')).toContainText('critical wound')
  await page.screenshot({ path: 'test-results/keyword-tooltip.png', fullPage: true })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Overlord', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/datasheet.png', fullPage: true })
  await page.goto('/factions/necrons/datasheets/overlord-with-translocation-shroud')
  await expect(page.getByRole('heading', { name: 'Overlord with Translocation Shroud', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Invulnerable save' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Translocation Shroud', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Resurrection Orb' })).toBeVisible()
  await page.screenshot({ path: 'test-results/translocation-shroud.png', fullPage: true })
})
