import { chooseCombatUnit, closeCombatBreakdown, openCombatBreakdown, openCombatControls, holdCombatCalculations } from './combat'
import { expect, test, type Locator, type Page } from '@playwright/test'
import { createRoster, retryUntilVisible, signUp, waitForRosterSave } from './account'

async function choose(page: Page, control: string, name: string) {
  const option = page.getByRole('option', { name, exact: true })
  await retryUntilVisible(option, () => page.getByRole('combobox', { name: control, exact: true }).click())
  await option.click()
  if (control.endsWith(' unit')) {
    await expect(
      page.getByRole('region', { name: control.split(' ')[0], exact: true }).getByRole('button', { name: 'Loadout', exact: true }),
    ).toBeEnabled()
    await openCombatControls(page)
  }
}

async function add(page: Page, name: string) {
  await page.getByLabel('Add a unit').fill(name)
  await waitForRosterSave(page, () =>
    page
      .getByRole('button', { name: `Add ${name}`, exact: true })
      .first()
      .click(),
  )
}

async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(
    await page
      .locator('aside, [role=dialog], [data-slot=roster-units], [data-slot=scroll-area-viewport]')
      .evaluateAll((panels) => panels.every((panel) => panel.scrollWidth <= panel.clientWidth + 1)),
  ).toBe(true)
}

async function estimate(scope: Page | Locator, phase: 'Shooting' | 'Melee') {
  await openCombatControls(scope)
  await openCombatBreakdown(scope)
  return scope.getByRole('region', { name: `${phase} estimate`, includeHidden: true })
}

test('Invasion Fleet hides unsupported rules in both roles while retaining calculated buffs', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await signUp(page, 'Invasion Fleet')
  await createRoster(page, { faction: 'Tyranids', detachment: /Invasion Fleet/ })
  await add(page, 'Hormagaunts')
  await page.locator('[data-unit="Hormagaunts"]').getByRole('button', { name: 'Hormagaunts', exact: true }).click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseCombatUnit(page, 'Defender', 'Necrons', 'Necron Warriors')
  const buffs = simulator.locator('[aria-label="Attacker buffs"], [aria-label="Defender buffs"]')
  const synapse = simulator.getByRole('switch', { name: 'Attacker Synapse', exact: true })
  await expect(synapse).toBeVisible()
  const melee = simulator.getByRole('region', { name: 'Melee results' })
  const damage = (await estimate(simulator, 'Melee')).locator('.readout').first()
  await expect(damage).toHaveText(/^\d+(?:\.\d+)?$/)
  await expect(melee).toHaveAttribute('aria-busy', 'false')
  const baseline = Number(await damage.textContent())
  await synapse.click()
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(baseline)
  await synapse.click()
  await expect.poll(async () => Number(await damage.textContent())).toBe(baseline)
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    await expect
      .poll(() =>
        simulator.getByLabel('Results summary').evaluate((element) => {
          const dialog = element.closest('[role=dialog]')
          return Boolean(dialog && Math.abs(element.getBoundingClientRect().bottom - dialog.getBoundingClientRect().bottom) <= 1)
        }),
      )
      .toBe(true)
    await closeCombatBreakdown(simulator)
    if (width === 390)
      expect(await simulator.getByLabel('Results summary').evaluate((element) => element.getBoundingClientRect().height)).toBeLessThan(160)
    for (const name of ['Hyper-adaptations', 'Sustained Hits', 'Lethal Hits', 'Hyper Adaptions', 'Not calculated'])
      for (const panel of await buffs.all()) await expect(panel).not.toContainText(name)
    await noOverflow(page)
    await synapse.scrollIntoViewIfNeeded()
    await simulator.screenshot({ path: `test-results/roster-simulator-invasion-fleet-${width}.png` })
    if (width === 390) {
      await simulator.locator('[data-simulator-scroll]').evaluate((element) => (element.scrollTop = element.scrollHeight))
      const footerTop = await simulator.getByLabel('Results summary').evaluate((element) => element.getBoundingClientRect().top)
      const modifiersBottom = await simulator
        .getByRole('region', { name: 'Applied modifiers' })
        .evaluate((element) => element.getBoundingClientRect().bottom)
      expect(modifiersBottom).toBeLessThanOrEqual(footerTop)
    }
  }
  await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
  await openCombatControls(simulator)
  await expect(simulator.getByRole('region', { name: 'Defender', exact: true }).locator('[data-combat-member]').first()).toContainText(
    'Hormagaunts',
  )
  for (const name of ['Hyper-adaptations', 'Sustained Hits', 'Lethal Hits', 'Hyper Adaptions', 'Not calculated'])
    for (const panel of await buffs.all()) await expect(panel).not.toContainText(name)
})

test('selected friendly support calculates against the marked enemy in both phases', async ({ page }) => {
  await signUp(page, 'Selected support')
  await createRoster(page, { faction: 'Aeldari', detachment: /Warhost/ })
  await add(page, 'Spiritseer')
  await add(page, 'Wraithguard')
  await page.locator('[data-unit="Wraithguard"]').getByRole('button', { name: 'Wraithguard', exact: true }).click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseCombatUnit(page, 'Defender', 'Space Marines', 'Land Raider')
  const buff = simulator.getByRole('switch', { name: 'Attacker Spirit Mark (Psychic)', exact: true })
  const rules = simulator.getByRole('region', { name: 'Attacker rules', exact: true })
  await expect(buff).not.toBeChecked()
  await expect(rules).toContainText('Spiritseer · Selected within 6" · Against the selected target')
  await expect(rules.getByRole('switch', { name: 'Attacker Psychic Guidance', exact: true })).not.toBeChecked()
  await expect(rules).not.toContainText('Not calculated')
  const results = ['Shooting results', 'Melee results'].map((name) => simulator.getByRole('region', { name }))
  const estimates = [await estimate(simulator, 'Shooting'), await estimate(simulator, 'Melee')]
  const baseline: number[] = []
  for (const [index, result] of results.entries()) {
    await expect(estimates[index].locator('.readout').first()).toHaveText(/^\d+(?:\.\d+)?$/)
    await expect(result).toHaveAttribute('aria-busy', 'false')
    baseline.push(Number(await estimates[index].locator('.readout').first().textContent()))
  }
  await buff.click()
  for (const [index, result] of results.entries()) {
    await expect(result).toContainText('Sustained Hits 1')
    await expect.poll(async () => Number(await estimates[index].locator('.readout').first().textContent())).toBeGreaterThan(baseline[index])
  }
  await buff.scrollIntoViewIfNeeded()
  await noOverflow(page)
  await simulator.screenshot({ path: 'test-results/roster-simulator-selected-support.png' })
  await page.setViewportSize({ width: 390, height: 1000 })
  await buff.scrollIntoViewIfNeeded()
  await noOverflow(page)
  await simulator.screenshot({ path: 'test-results/roster-simulator-selected-support-390.png' })
  await buff.click()
  for (const [index] of results.entries())
    await expect.poll(async () => Number(await estimates[index].locator('.readout').first().textContent())).toBe(baseline[index])
  await choose(page, 'Attacker unit', 'Spiritseer')
  await expect(rules).not.toContainText('Spirit Mark')
  await choose(page, 'Attacker unit', 'Wraithguard')
  await expect(buff).not.toBeChecked()
  await buff.click()
  await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
  await openCombatControls(simulator)
  await expect(simulator.getByRole('region', { name: 'Defender rules', exact: true })).not.toContainText('Spirit Mark')
  await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
  await openCombatControls(simulator)
  await expect(buff).toBeChecked()
})

test('Aeldari weapon buffs calculate their named and existing-ability effects', async ({ page }) => {
  await signUp(page, 'Aeldari')
  await createRoster(page, { faction: 'Aeldari', detachment: /Warhost/ })
  await add(page, 'Asurmen')
  await page.locator('[data-unit="Asurmen"]').getByRole('button', { name: 'Asurmen', exact: true }).click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseCombatUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const hand = simulator.getByRole('switch', { name: 'Attacker Hand of Asuryan', exact: true })
  const blitz = simulator.getByRole('switch', { name: 'Attacker Blitzing Firepower', exact: true })
  await expect(hand).not.toBeChecked()
  await expect(blitz).not.toBeChecked()
  const shooting = simulator.getByRole('region', { name: 'Shooting results' })
  const damage = (await estimate(simulator, 'Shooting')).locator('.readout').first()
  await expect(damage).toHaveText(/^\d+(?:\.\d+)?$/)
  await expect(shooting).toHaveAttribute('aria-busy', 'false')
  const baseline = Number(await damage.textContent())
  await hand.click()
  await expect(shooting.getByRole('button', { name: 'D 3, modified from 2 by Hand of Asuryan', exact: true })).toBeVisible()
  await expect(shooting).toContainText('ANTI-INFANTRY 5+')
  await expect(shooting).toContainText('DEVASTATING WOUNDS')
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(baseline)
  await expect(shooting).toHaveAttribute('aria-busy', 'false')
  const activated = Number(await damage.textContent())
  await blitz.click()
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(activated)
  await expect(simulator.getByRole('region', { name: 'Attacker rules', exact: true })).toContainText('Target within 12"')
  expect(
    await simulator.getByRole('region', { name: 'Attacker buffs', exact: true }).evaluate((element) => {
      const conditions = document.querySelector('[aria-label="Modifiers"]')!
      return Boolean(element.compareDocumentPosition(conditions) & Node.DOCUMENT_POSITION_FOLLOWING)
    }),
  ).toBe(true)
  await blitz.scrollIntoViewIfNeeded()
  await simulator.screenshot({ path: 'test-results/roster-simulator-aeldari-buffs.png' })
  await page.setViewportSize({ width: 390, height: 1000 })
  await noOverflow(page)
  await simulator.screenshot({ path: 'test-results/roster-simulator-aeldari-buffs-390.png' })
  await hand.click()
  await blitz.click()
  await expect.poll(async () => Number(await damage.textContent())).toBe(baseline)
  await simulator.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Back to roster', exact: true }).click()
  await expect(page.locator('[data-unit="Asurmen"]')).toBeVisible()
})

for (const width of [1440, 390, 900]) {
  test(`roster simulations preserve the saved loadout at ${width}px`, async ({ browser, page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await signUp(page, 'Simulator')
    await createRoster(page, { faction: 'Space Marines', detachment: /Gladius Task Force/ })
    await add(page, 'Intercessor Squad')
    if (width < 1300) await page.getByRole('dialog', { name: 'Add units' }).getByRole('button', { name: 'Close' }).click()
    await noOverflow(page)
    const card = page.locator('[data-unit="Intercessor Squad"]')
    await card.getByRole('button', { name: 'Intercessor Squad', exact: true }).click()
    const pane = page.locator('aside[aria-label="Loadout"]')
    await waitForRosterSave(page, () =>
      pane
        .getByRole('group', { name: 'Intercessor Squad Weapon 1' })
        .getByRole('button', { name: 'Select Plasma pistol', exact: true })
        .click(),
    )
    await waitForRosterSave(page, () => pane.getByRole('button', { name: 'More models in Intercessor Squad', exact: true }).click())
    await expect(pane.getByLabel('Intercessor Squad models', { exact: true })).toHaveText('6')
    await noOverflow(page)
    await page.screenshot({ path: `test-results/roster-simulator-entry-${width}.png`, fullPage: true })

    const serverContext = await browser.newContext({
      javaScriptEnabled: false,
      storageState: await page.context().storageState(),
      viewport: { width, height: 1000 },
    })
    const serverPage = await serverContext.newPage()
    await serverPage.goto(page.url())
    await noOverflow(serverPage)
    await serverPage.screenshot({ path: `test-results/roster-simulator-ssr-${width}.png`, fullPage: true })
    await serverContext.close()

    await pane.getByRole('button', { name: 'Simulate combat', exact: true }).click()
    const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
    await expect(simulator.getByLabel('Attacker models', { exact: true })).toHaveText('6')
    await expect(simulator.getByLabel('Attacker faction', { exact: true })).toContainText('Space Marines')
    await chooseCombatUnit(page, 'Defender', 'Necrons', 'Canoptek Reanimator')
    const shooting = simulator.getByRole('region', { name: 'Shooting results' })
    const melee = simulator.getByRole('region', { name: 'Melee results' })
    await expect(shooting).toHaveAttribute('aria-busy', 'false')
    await expect(shooting).toContainText('5× ➤ Bolt Rifle - Focused Fire')
    await expect(shooting).toContainText('Plasma pistol')
    await expect(melee).toContainText('6× Knives and Fists')
    await expect(
      simulator.getByRole('region', { name: 'Defender', exact: true }).locator('[data-characteristic="FNP"] .readout'),
    ).toHaveText('4+')
    await (await estimate(simulator, 'Shooting')).getByRole('button', { name: /Wounds lost: .*Show probabilities/ }).click()
    const chart = page.getByRole('dialog', { name: 'Shooting · Wounds lost probabilities', exact: true })
    await expect(chart).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(chart).toBeHidden()
    await expect(simulator).toBeVisible()
    await noOverflow(page)
    await simulator.screenshot({ path: `test-results/roster-simulator-${width}.png` })

    const previousDamage = await (await estimate(simulator, 'Shooting')).locator('.readout').first().textContent()
    const calculation = await holdCombatCalculations(page)
    await simulator.getByRole('button', { name: 'More attacker models' }).click()
    await calculation.waitForStart()
    await expect(shooting).toHaveAttribute('aria-busy', 'true')
    await expect((await estimate(simulator, 'Shooting')).locator('.readout').first()).toHaveText(previousDamage!)
    await expect(simulator.getByLabel('Attacker models', { exact: true })).toHaveText('7')
    await calculation.release()
    await expect(shooting).toHaveAttribute('aria-busy', 'false')
    await expect(shooting).toContainText('6× ➤ Bolt Rifle - Focused Fire')

    await simulator.getByRole('region', { name: 'Attacker', exact: true }).getByRole('button', { name: 'Loadout', exact: true }).click()
    const loadout = page.getByRole('dialog', { name: 'Attacker · Intercessor Squad', exact: true })
    const powerFist = loadout
      .getByRole('group', { name: 'Intercessor Squad Weapon 2' })
      .getByRole('button', { name: 'Select Power fist', exact: true })
    await powerFist.click()
    await expect(powerFist).toHaveAttribute('aria-pressed', 'true')
    await noOverflow(page)
    await loadout.screenshot({ path: `test-results/roster-simulator-loadout-${width}.png` })
    await loadout.getByRole('button', { name: 'Close', exact: true }).click()
    await expect(melee).toHaveAttribute('aria-busy', 'false')
    await expect(melee).toContainText('Power fist')
    await expect(melee).toContainText('6× Knives and Fists')
    await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
    await openCombatControls(simulator)
    await expect(simulator.getByLabel('Defender models', { exact: true })).toHaveText('7')
    await expect(simulator.getByLabel('Defender faction', { exact: true })).toContainText('Space Marines')
    await expect(shooting).toHaveAttribute('aria-busy', 'false')
    await page.keyboard.press('Escape')
    await expect(pane.getByLabel('Intercessor Squad models', { exact: true })).toHaveText('6')
    await expect(card).toContainText('Plasma pistol')
    await expect(card).not.toContainText('Power fist')
    await pane.getByRole('button', { name: 'Simulate combat', exact: true }).click()
    await expect(simulator.getByLabel('Attacker models', { exact: true })).toHaveText('6')
    await simulator.getByRole('button', { name: 'Close', exact: true }).click()
    await page.reload()
    await expect(card).toContainText('5x Bolt Rifle')
    await expect(card).toContainText('Plasma pistol')
  })
}

test('roster simulations inherit enhancements and attached-unit context', async ({ page }) => {
  await signUp(page, 'Context')
  await createRoster(page, { faction: 'Necrons', detachment: /Cursed Legion/ })
  await add(page, 'Immortals')
  await add(page, 'Overlord')
  const lord = page.locator('[data-unit="Overlord"]')
  await lord.getByRole('button', { name: 'Overlord', exact: true }).click()
  const pane = page.locator('aside[aria-label="Loadout"]')
  await waitForRosterSave(page, () => pane.getByRole('button', { name: 'Select Destroyer Ankh', exact: true }).click())
  await lord.getByRole('button', { name: 'Attach Overlord to unit' }).click()
  await waitForRosterSave(page, () => page.getByRole('menuitem', { name: 'Immortals', exact: true }).click())
  await pane.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseCombatUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const melee = simulator.getByRole('region', { name: 'Melee results' })
  await expect(melee).toHaveAttribute('aria-busy', 'false')
  await expect(melee.getByRole('button', { name: 'A 6, modified from 4 by Destroyer Ankh', exact: true })).toBeVisible()
  const damage = (await estimate(simulator, 'Melee')).locator('.readout').first()
  await expect(damage).toHaveText(/^\d+\.\d+$/)
  const enhancedDamage = Number(await damage.textContent())
  await choose(page, 'Attacker Enhancements', 'No enhancement')
  await expect(melee).toHaveAttribute('aria-busy', 'false')
  await expect(melee.getByRole('button', { name: /modified from 4 by Destroyer Ankh/ })).toHaveCount(0)
  await expect.poll(async () => Number(await damage.textContent())).toBeLessThan(enhancedDamage)
  await simulator.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(lord).toContainText('Destroyer Ankh')
  await pane.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  await choose(page, 'Attacker unit', 'Immortals')
  await simulator.getByRole('region', { name: 'Attacker', exact: true }).getByRole('button', { name: 'Loadout', exact: true }).click()
  const bodyguard = page.getByRole('dialog', { name: 'Attacker · Immortals', exact: true })
  await expect(bodyguard.getByRole('button', { name: 'M 7", modified from 5" by Destroyer Ankh', exact: true })).toBeVisible()
  await bodyguard.screenshot({ path: 'test-results/roster-simulator-inherited.png' })
})

test('roster buffs apply conditional shooting bonuses and defensive stratagems', async ({ page }) => {
  await signUp(page, 'Buffs')
  await createRoster(page, { faction: 'Space Marines', detachment: /Gladius Task Force/ })
  await add(page, 'Intercessor Squad')
  await page.locator('[data-unit="Intercessor Squad"]').getByRole('button', { name: 'Intercessor Squad', exact: true }).click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseCombatUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const shooting = simulator.getByRole('region', { name: 'Shooting results' })
  const damage = (await estimate(simulator, 'Shooting')).locator('.readout').first()
  await expect(damage).toHaveText('2.22')
  const storm = simulator.getByRole('button', { name: 'Attacker Storm of devastation rules', exact: true })
  await expect(simulator.getByText('IGNORES COVER', { exact: false })).toHaveCount(0)
  await storm.hover()
  const tooltip = page.getByRole('tooltip').filter({ hasText: 'Storm of devastation' })
  await expect(tooltip).toContainText('IGNORES COVER')
  await storm.click()
  await page.screenshot({ path: 'test-results/roster-simulator-rule-tooltip.png' })
  await page.keyboard.press('Escape')
  await expect(tooltip).toBeHidden()
  await expect(simulator).toBeVisible()
  await page.keyboard.press('Tab')
  await storm.focus()
  await expect(tooltip).toContainText('IGNORES COVER')
  const stormChoice = simulator.getByRole('switch', { name: 'Attacker Storm of devastation', exact: true })
  await expect(stormChoice).not.toBeChecked()
  await page.keyboard.press('Escape')
  await expect(simulator).toBeVisible()
  await simulator.getByRole('tab', { name: /^Shooting/ }).click()
  const cover = simulator.getByRole('button', { name: 'Cover (−1 BS)', exact: true })
  await cover.click()
  await expect.poll(async () => Number(await damage.textContent())).toBeLessThan(2.22)
  const covered = Number(await damage.textContent())
  await stormChoice.click()
  await expect(shooting).toContainText('IGNORES COVER')
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(covered)
  await stormChoice.click()
  await cover.click()
  await expect(damage).toHaveText('2.22')
  await simulator.locator('[data-combat-buffs] > summary').scrollIntoViewIfNeeded()
  await simulator.screenshot({ path: 'test-results/roster-simulator-buffs.png' })
  await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
  await openCombatControls(simulator)
  await expect(damage).toHaveText('2.22')
  await simulator.getByRole('switch', { name: 'Defender Armour of Contempt', exact: true }).click()
  await expect.poll(async () => Number(await damage.textContent())).toBeLessThan(2.22)
  await expect(shooting.getByRole('button', { name: 'AP 0, modified from -1 by Armour of Contempt', exact: true })).toBeVisible()
  await simulator.getByRole('switch', { name: 'Defender Armour of Contempt', exact: true }).click()
  await expect(damage).toHaveText('2.22')
  await expect(simulator.getByRole('switch', { name: 'Attacker Armour of Contempt', exact: true })).toHaveCount(0)
  await simulator.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.locator('[data-roster-builder]')).toHaveAttribute('data-saving', 'false')
})

test('a support stratagem requires its source and applies to its eligible recipient', async ({ page }) => {
  await signUp(page, 'Support')
  await createRoster(page, { faction: 'Necrons', detachment: /Canoptek Court/ })
  await add(page, 'Immortals')
  const immortals = page.locator('[data-unit="Immortals"]').getByRole('button', { name: 'Immortals', exact: true })
  await immortals.click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await openCombatControls(simulator)
  await expect(simulator.getByRole('region', { name: 'Attacker rules', exact: true })).toBeVisible()
  await expect(simulator.getByRole('switch', { name: 'Attacker Solar Pulse', exact: true })).toHaveCount(0)
  await simulator.getByRole('button', { name: 'Close', exact: true }).click()
  await add(page, 'Chronomancer')
  await immortals.click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  await chooseCombatUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const pulse = simulator.getByRole('switch', { name: 'Attacker Solar Pulse', exact: true })
  await expect(pulse).not.toBeChecked()
  await simulator.getByRole('tab', { name: /^Shooting/ }).click()
  await simulator.getByRole('button', { name: 'Cover (−1 BS)', exact: true }).click()
  const shooting = simulator.getByRole('region', { name: 'Shooting results' })
  const damage = (await estimate(simulator, 'Shooting')).locator('.readout').first()
  await expect(damage).toHaveText(/^\d+\.\d+$/)
  await expect(shooting).toHaveAttribute('aria-busy', 'false')
  const baseline = Number(await damage.textContent())
  await pulse.click()
  await expect(shooting).toContainText('IGNORES COVER')
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(baseline)
  await pulse.scrollIntoViewIfNeeded()
  await simulator.screenshot({ path: 'test-results/roster-simulator-support-stratagem.png' })
})
