import { expect, test, type Page } from '@playwright/test'
import { chooseUnit, createRoster, retryUntilVisible, signUp, waitForRosterSave } from './account'

async function choose(page: Page, control: string, name: string) {
  const option = page.getByRole('option', { name, exact: true })
  await retryUntilVisible(option, () => page.getByRole('combobox', { name: control, exact: true }).click())
  await option.click()
}

async function add(page: Page, name: string) {
  await page.getByLabel('Add a unit').fill(name)
  await waitForRosterSave(page, () =>
    page
      .getByRole('button', { name: `Add ${name}`, exact: true })
      .first()
      .click(),
  )
}

async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(
    await page
      .locator('aside, [role=dialog], [data-slot=roster-units], [data-slot=scroll-area-viewport]')
      .evaluateAll((panels) => panels.every((panel) => panel.scrollWidth <= panel.clientWidth + 1)),
  ).toBe(true)
}

test('unsupported enhancements stay out of the simulator without changing the roster loadout editor', async ({ page }) => {
  await signUp(page, 'Exclusions')
  await createRoster(page, { faction: 'Space Marines', detachment: /Bastion Task Force/ })
  await add(page, 'Captain')
  await page.locator('[data-unit="Captain"]').getByRole('button', { name: 'Captain', exact: true }).click()
  await expect(page.locator('aside[aria-label="Loadout"]')).toContainText('Eye of the Primarch')
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  await chooseUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await expect(simulator.getByRole('switch', { name: 'Attacker Finest Hour', exact: true })).toBeVisible()
  await expect(simulator.getByRole('combobox', { name: 'Attacker Bastion Task Force Enhancements', exact: true })).toHaveCount(0)
  await expect(simulator.getByRole('region', { name: 'Attacker rules', exact: true })).not.toContainText('Eye of the Primarch')
  await simulator.getByRole('region', { name: 'Attacker rules', exact: true }).scrollIntoViewIfNeeded()
  await simulator.screenshot({ path: 'test-results/roster-simulator-exclusions.png' })
})

test('Invasion Fleet hides unsupported rules in both roles while retaining calculated buffs', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await signUp(page, 'Invasion Fleet')
  await createRoster(page, { faction: 'Tyranids', detachment: /Invasion Fleet/ })
  await add(page, 'Hormagaunts')
  await page.locator('[data-unit="Hormagaunts"]').getByRole('button', { name: 'Hormagaunts', exact: true }).click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const buffs = simulator.getByRole('region', { name: 'Buffs', exact: true })
  const synapse = simulator.getByRole('switch', { name: 'Attacker Synapse', exact: true })
  await expect(synapse).toBeVisible()
  const melee = simulator.getByRole('region', { name: 'Melee results' })
  const damage = melee.locator('.readout').first()
  await expect(damage).toHaveText(/^\d+(?:\.\d+)?$/)
  await expect(melee).toHaveAttribute('aria-busy', 'false')
  const baseline = Number(await damage.textContent())
  await synapse.click()
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(baseline)
  await synapse.click()
  await expect.poll(async () => Number(await damage.textContent())).toBe(baseline)
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    for (const name of ['Hyper-adaptations', 'Sustained Hits', 'Lethal Hits', 'Hyper Adaptions', 'Not calculated'])
      await expect(buffs).not.toContainText(name)
    await noOverflow(page)
    await synapse.scrollIntoViewIfNeeded()
    await simulator.screenshot({ path: `test-results/roster-simulator-invasion-fleet-${width}.png` })
  }
  await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
  await expect(simulator.getByRole('combobox', { name: 'Defender unit', exact: true })).toContainText('Hormagaunts')
  for (const name of ['Hyper-adaptations', 'Sustained Hits', 'Lethal Hits', 'Hyper Adaptions', 'Not calculated'])
    await expect(buffs).not.toContainText(name)
})

test('selected friendly support calculates against the marked enemy in both phases', async ({ page }) => {
  await signUp(page, 'Selected support')
  await createRoster(page, { faction: 'Aeldari', detachment: /Warhost/ })
  await add(page, 'Spiritseer')
  await add(page, 'Wraithguard')
  await page.locator('[data-unit="Wraithguard"]').getByRole('button', { name: 'Wraithguard', exact: true }).click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseUnit(page, 'Defender', 'Space Marines', 'Land Raider')
  const buff = simulator.getByRole('switch', { name: 'Attacker Spirit Mark (Psychic)', exact: true })
  const rules = simulator.getByRole('region', { name: 'Attacker rules', exact: true })
  await expect(buff).not.toBeChecked()
  await expect(rules).toContainText('Spiritseer · Selected within 6" · Against the selected target')
  await expect(rules.getByRole('switch', { name: 'Attacker Psychic Guidance', exact: true })).not.toBeChecked()
  await expect(rules).not.toContainText('Not calculated')
  const results = ['Shooting results', 'Melee results'].map((name) => simulator.getByRole('region', { name }))
  const baseline: number[] = []
  for (const result of results) {
    await expect(result.locator('.readout').first()).toHaveText(/^\d+(?:\.\d+)?$/)
    await expect(result).toHaveAttribute('aria-busy', 'false')
    baseline.push(Number(await result.locator('.readout').first().textContent()))
  }
  await buff.click()
  for (const [index, result] of results.entries()) {
    await expect(result).toContainText('Sustained Hits 1')
    await expect.poll(async () => Number(await result.locator('.readout').first().textContent())).toBeGreaterThan(baseline[index])
  }
  await buff.scrollIntoViewIfNeeded()
  await noOverflow(page)
  await simulator.screenshot({ path: 'test-results/roster-simulator-selected-support.png' })
  await page.setViewportSize({ width: 390, height: 1000 })
  await buff.scrollIntoViewIfNeeded()
  await noOverflow(page)
  await simulator.screenshot({ path: 'test-results/roster-simulator-selected-support-390.png' })
  await buff.click()
  for (const [index, result] of results.entries())
    await expect.poll(async () => Number(await result.locator('.readout').first().textContent())).toBe(baseline[index])
  await choose(page, 'Attacker unit', 'Spiritseer')
  await expect(rules).not.toContainText('Spirit Mark')
  await choose(page, 'Attacker unit', 'Wraithguard')
  await expect(buff).not.toBeChecked()
  await buff.click()
  await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
  await expect(simulator.getByRole('region', { name: 'Defender rules', exact: true })).not.toContainText('Spirit Mark')
  await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
  await expect(buff).toBeChecked()
})

test('Aeldari weapon buffs calculate their named and existing-ability effects', async ({ page }) => {
  await signUp(page, 'Aeldari')
  await createRoster(page, { faction: 'Aeldari', detachment: /Warhost/ })
  await add(page, 'Asurmen')
  await page.locator('[data-unit="Asurmen"]').getByRole('button', { name: 'Asurmen', exact: true }).click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const hand = simulator.getByRole('switch', { name: 'Attacker Hand of Asuryan', exact: true })
  const blitz = simulator.getByRole('switch', { name: 'Attacker Blitzing Firepower', exact: true })
  await expect(hand).not.toBeChecked()
  await expect(blitz).not.toBeChecked()
  const shooting = simulator.getByRole('region', { name: 'Shooting results' })
  const damage = shooting.locator('.readout').first()
  await expect(damage).toHaveText(/^\d+(?:\.\d+)?$/)
  await expect(shooting).toHaveAttribute('aria-busy', 'false')
  const baseline = Number(await damage.textContent())
  await hand.click()
  await expect(shooting.getByRole('button', { name: 'D 3, modified from 2 by Hand of Asuryan', exact: true })).toBeVisible()
  await expect(shooting).toContainText('ANTI-INFANTRY 5+')
  await expect(shooting).toContainText('DEVASTATING WOUNDS')
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(baseline)
  await expect(shooting).toHaveAttribute('aria-busy', 'false')
  const activated = Number(await damage.textContent())
  await blitz.click()
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(activated)
  await expect(simulator.getByRole('region', { name: 'Attacker rules', exact: true })).toContainText('Target within 12"')
  expect(
    await simulator.getByRole('region', { name: 'Buffs', exact: true }).evaluate((element) => {
      const conditions = document.querySelector('[aria-label="Conditions"]')!
      return Boolean(element.compareDocumentPosition(conditions) & Node.DOCUMENT_POSITION_FOLLOWING)
    }),
  ).toBe(true)
  await blitz.scrollIntoViewIfNeeded()
  await simulator.screenshot({ path: 'test-results/roster-simulator-aeldari-buffs.png' })
  await page.setViewportSize({ width: 390, height: 1000 })
  await noOverflow(page)
  await simulator.screenshot({ path: 'test-results/roster-simulator-aeldari-buffs-390.png' })
  await hand.click()
  await blitz.click()
  await expect.poll(async () => Number(await damage.textContent())).toBe(baseline)
  await simulator.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Back to roster', exact: true }).click()
  await expect(page.locator('[data-unit="Asurmen"]')).toBeVisible()
})

for (const width of [1440, 390, 900]) {
  test(`roster simulations preserve the saved loadout at ${width}px`, async ({ browser, page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await signUp(page, 'Simulator')
    await createRoster(page, { faction: 'Space Marines', detachment: /Gladius Task Force/ })
    await add(page, 'Intercessor Squad')
    if (width < 1300) await page.getByRole('dialog', { name: 'Add units' }).getByRole('button', { name: 'Close' }).click()
    await noOverflow(page)
    const card = page.locator('[data-unit="Intercessor Squad"]')
    await card.getByRole('button', { name: 'Intercessor Squad', exact: true }).click()
    const pane = page.locator('aside[aria-label="Loadout"]')
    await waitForRosterSave(page, () => pane.getByRole('button', { name: 'Select Power fist', exact: true }).click())
    await waitForRosterSave(page, () => pane.getByRole('button', { name: 'More models in Intercessor Squad', exact: true }).click())
    await expect(pane.getByLabel('Intercessor Squad models', { exact: true })).toHaveText('6')
    await noOverflow(page)
    await page.screenshot({ path: `test-results/roster-simulator-entry-${width}.png`, fullPage: true })

    const serverContext = await browser.newContext({
      javaScriptEnabled: false,
      storageState: await page.context().storageState(),
      viewport: { width, height: 1000 },
    })
    const serverPage = await serverContext.newPage()
    await serverPage.goto(page.url())
    await noOverflow(serverPage)
    await serverPage.screenshot({ path: `test-results/roster-simulator-ssr-${width}.png`, fullPage: true })
    await serverContext.close()

    await pane.getByRole('button', { name: 'Simulate combat', exact: true }).click()
    const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
    await expect(simulator.getByLabel('Attacker models', { exact: true })).toHaveText('6')
    await expect(simulator.getByLabel('Attacker faction', { exact: true })).toContainText('Space Marines')
    await chooseUnit(page, 'Defender', 'Necrons', 'Canoptek Reanimator')
    const shooting = simulator.getByRole('region', { name: 'Shooting results' })
    const melee = simulator.getByRole('region', { name: 'Melee results' })
    await expect(shooting).toHaveAttribute('aria-busy', 'false')
    await expect(shooting).toContainText('6× Bolt Rifle')
    await expect(melee).toContainText('Power fist')
    await expect(
      simulator.getByRole('region', { name: 'Defender', exact: true }).locator('[data-characteristic="FNP"] .readout'),
    ).toHaveText('4+')
    await shooting.getByRole('button', { name: /Wounds lost: .*Show probabilities/ }).click()
    const chart = page.getByRole('dialog', { name: 'Shooting · Wounds lost probabilities', exact: true })
    await expect(chart).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(chart).toBeHidden()
    await expect(simulator).toBeVisible()
    await noOverflow(page)
    await simulator.screenshot({ path: `test-results/roster-simulator-${width}.png` })

    let release = () => {}
    const gate = new Promise<void>((resolve) => {
      release = resolve
    })
    let intercepted = false
    await page.route('**/*', async (route) => {
      if (route.request().method() === 'POST' && route.request().postData()?.includes('85b1-eb9a-17a6-e5be')) {
        intercepted = true
        await gate
      }
      await route.continue()
    })
    await simulator.getByRole('button', { name: 'More attacker models' }).click()
    await expect.poll(() => intercepted).toBe(true)
    await expect(shooting).toHaveAttribute('aria-busy', 'true')
    await expect(shooting).toContainText('6× Bolt Rifle')
    await expect(simulator.getByLabel('Attacker models', { exact: true })).toHaveText('7')
    release()
    await expect(shooting).toHaveAttribute('aria-busy', 'false')
    await page.unrouteAll({ behavior: 'wait' })
    await expect(shooting).toContainText('7× Bolt Rifle')

    await simulator.getByRole('region', { name: 'Attacker', exact: true }).getByRole('button', { name: 'Loadout', exact: true }).click()
    const loadout = page.getByRole('dialog', { name: 'Attacker · Intercessor Squad', exact: true })
    const chainsword = loadout
      .getByRole('group', { name: 'Intercessor Squad Weapon 2', exact: true })
      .getByRole('button', { name: /^Select Astartes chainsword$/i })
    await chainsword.click()
    await expect(chainsword).toHaveAttribute('aria-pressed', 'true')
    await noOverflow(page)
    await loadout.screenshot({ path: `test-results/roster-simulator-loadout-${width}.png` })
    await loadout.getByRole('button', { name: 'Close', exact: true }).click()
    await expect(melee).toHaveAttribute('aria-busy', 'false')
    await expect(melee).toContainText(/Astartes chainsword/i)
    await expect(melee).not.toContainText('Power fist')
    await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
    await expect(simulator.getByLabel('Defender models', { exact: true })).toHaveText('7')
    await expect(simulator.getByLabel('Defender faction', { exact: true })).toContainText('Space Marines')
    await expect(shooting).toHaveAttribute('aria-busy', 'false')
    await page.keyboard.press('Escape')
    await expect(pane.getByLabel('Intercessor Squad models', { exact: true })).toHaveText('6')
    await expect(card).toContainText('Power fist')
    await expect(card).not.toContainText(/Astartes chainsword/i)
    await pane.getByRole('button', { name: 'Simulate combat', exact: true }).click()
    await expect(simulator.getByLabel('Attacker models', { exact: true })).toHaveText('6')
    await simulator.getByRole('button', { name: 'Close', exact: true }).click()
    await page.reload()
    await expect(card).toContainText('6x Bolt Rifle')
    await expect(card).toContainText('Power fist')
  })
}

test('roster simulations inherit enhancements and attached-unit context', async ({ page }) => {
  await signUp(page, 'Context')
  await createRoster(page, { faction: 'Necrons', detachment: /Cursed Legion/ })
  await add(page, 'Immortals')
  await add(page, 'Overlord')
  const lord = page.locator('[data-unit="Overlord"]')
  await lord.getByRole('button', { name: 'Overlord', exact: true }).click()
  const pane = page.locator('aside[aria-label="Loadout"]')
  await waitForRosterSave(page, () => pane.getByRole('button', { name: 'Select Destroyer Ankh', exact: true }).click())
  await lord.getByRole('button', { name: 'Attach Overlord to unit' }).click()
  await waitForRosterSave(page, () => page.getByRole('menuitem', { name: 'Immortals', exact: true }).click())
  await pane.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const melee = simulator.getByRole('region', { name: 'Melee results' })
  await expect(melee).toHaveAttribute('aria-busy', 'false')
  await expect(melee.getByRole('button', { name: 'A 6, modified from 4 by Destroyer Ankh', exact: true })).toBeVisible()
  const damage = melee.locator('.readout').first()
  await expect(damage).toHaveText(/^\d+\.\d+$/)
  const enhancedDamage = Number(await damage.textContent())
  await choose(page, 'Attacker Enhancements', 'No enhancement')
  await expect(melee).toHaveAttribute('aria-busy', 'false')
  await expect(melee.getByRole('button', { name: /modified from 4 by Destroyer Ankh/ })).toHaveCount(0)
  await expect.poll(async () => Number(await damage.textContent())).toBeLessThan(enhancedDamage)
  await simulator.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(lord).toContainText('Destroyer Ankh')
  await pane.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  await choose(page, 'Attacker unit', 'Immortals')
  await simulator.getByRole('region', { name: 'Attacker', exact: true }).getByRole('button', { name: 'Loadout', exact: true }).click()
  const bodyguard = page.getByRole('dialog', { name: 'Attacker · Immortals', exact: true })
  await expect(bodyguard.getByRole('button', { name: 'M 7", modified from 5" by Destroyer Ankh', exact: true })).toBeVisible()
  await bodyguard.screenshot({ path: 'test-results/roster-simulator-inherited.png' })
})

test('roster buffs apply conditional shooting bonuses and defensive stratagems', async ({ page }) => {
  await signUp(page, 'Buffs')
  await createRoster(page, { faction: 'Space Marines', detachment: /Gladius Task Force/ })
  await add(page, 'Intercessor Squad')
  await page.locator('[data-unit="Intercessor Squad"]').getByRole('button', { name: 'Intercessor Squad', exact: true }).click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await chooseUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const shooting = simulator.getByRole('region', { name: 'Shooting results' })
  const damage = shooting.locator('.readout').first()
  await expect(damage).toHaveText('1.67')
  const rule = simulator.getByRole('button', { name: 'Attacker Hail of Bolts rules', exact: true })
  const buff = simulator.getByRole('switch', { name: 'Attacker Hail of Bolts', exact: true })
  await expect(simulator.getByText('have +2 A', { exact: false })).toHaveCount(0)
  await rule.hover()
  const tooltip = page.getByRole('tooltip').filter({ hasText: 'Hail of Bolts' })
  await expect(tooltip).toContainText('have +2 A')
  await rule.click()
  await expect(buff).not.toBeChecked()
  await page.screenshot({ path: 'test-results/roster-simulator-rule-tooltip.png' })
  await page.keyboard.press('Escape')
  await expect(tooltip).toBeHidden()
  await expect(simulator).toBeVisible()
  await page.keyboard.press('Tab')
  const storm = simulator.getByRole('button', { name: 'Attacker Storm of Fire rules', exact: true })
  await storm.focus()
  await expect(page.getByRole('tooltip').filter({ hasText: 'Storm of Fire' })).toContainText('Devastator Doctrine')
  await expect(simulator.getByRole('combobox', { name: 'Attacker Storm of Fire', exact: true })).toContainText('Off')
  await page.keyboard.press('Escape')
  await expect(simulator).toBeVisible()
  await simulator.getByRole('switch', { name: 'Attacker Hail of Bolts', exact: true }).click()
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(3)
  await simulator.getByRole('switch', { name: 'Attacker Hail of Bolts', exact: true }).click()
  await expect(damage).toHaveText('1.67')
  await choose(page, 'Attacker Storm of Fire', 'Active')
  await expect(shooting).toContainText('IGNORES COVER')
  await expect(shooting.getByRole('button', { name: /AP -2, modified/ })).toHaveCount(0)
  await choose(page, 'Attacker Storm of Fire', 'With the Devastator Doctrine')
  await expect(shooting.getByRole('button', { name: 'AP -2, modified from -1 by Storm of Fire', exact: true })).toBeVisible()
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(2.1)
  await simulator.getByRole('heading', { name: 'Attacker rules & buffs', exact: true }).scrollIntoViewIfNeeded()
  await simulator.screenshot({ path: 'test-results/roster-simulator-buffs.png' })
  await simulator.getByRole('button', { name: 'Swap attacker and defender' }).click()
  await expect(damage).toHaveText('1.67')
  await simulator.getByRole('switch', { name: 'Defender Armour of Contempt', exact: true }).click()
  await expect.poll(async () => Number(await damage.textContent())).toBeLessThan(1.2)
  await expect(shooting.getByRole('button', { name: 'AP 0, modified from -1 by Armour of Contempt', exact: true })).toBeVisible()
  await simulator.getByRole('switch', { name: 'Defender Armour of Contempt', exact: true }).click()
  await expect(damage).toHaveText('1.67')
  await expect(simulator.getByRole('switch', { name: 'Attacker Armour of Contempt', exact: true })).toHaveCount(0)
  await simulator.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.locator('[data-roster-builder]')).toHaveAttribute('data-saving', 'false')
})

test('a support stratagem requires its source and applies to its eligible recipient', async ({ page }) => {
  await signUp(page, 'Support')
  await createRoster(page, { faction: 'Necrons', detachment: /Canoptek Court/ })
  await add(page, 'Immortals')
  const immortals = page.locator('[data-unit="Immortals"]').getByRole('button', { name: 'Immortals', exact: true })
  await immortals.click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  const simulator = page.getByRole('dialog', { name: 'Combat simulator', exact: true })
  await expect(simulator.getByRole('region', { name: 'Attacker rules', exact: true })).toBeVisible()
  await expect(simulator.getByRole('switch', { name: 'Attacker Solar Pulse', exact: true })).toHaveCount(0)
  await simulator.getByRole('button', { name: 'Close', exact: true }).click()
  await add(page, 'Chronomancer')
  await immortals.click()
  await page.getByRole('button', { name: 'Simulate combat', exact: true }).click()
  await chooseUnit(page, 'Defender', 'Space Marines', 'Intercessor Squad')
  const pulse = simulator.getByRole('switch', { name: 'Attacker Solar Pulse', exact: true })
  await expect(pulse).not.toBeChecked()
  await simulator.getByRole('button', { name: 'Cover (−1 BS)', exact: true }).click()
  const shooting = simulator.getByRole('region', { name: 'Shooting results' })
  const damage = shooting.locator('.readout').first()
  await expect(damage).toHaveText(/^\d+\.\d+$/)
  await expect(shooting).toHaveAttribute('aria-busy', 'false')
  const baseline = Number(await damage.textContent())
  await pulse.click()
  await expect(shooting).toContainText('IGNORES COVER')
  await expect.poll(async () => Number(await damage.textContent())).toBeGreaterThan(baseline)
  await pulse.scrollIntoViewIfNeeded()
  await simulator.screenshot({ path: 'test-results/roster-simulator-support-stratagem.png' })
})
