default_platform(:ios)
opt_out_usage

platform :ios do
  lane :upload do |options|
    app_identifier = 'gg.praetorium'
    key_path = ENV.fetch('APP_STORE_CONNECT_KEY_PATH')

    api_key = app_store_connect_api_key(
      key_id: ENV.fetch('APP_STORE_CONNECT_KEY_ID'),
      issuer_id: ENV.fetch('APP_STORE_CONNECT_ISSUER_ID'),
      key_filepath: key_path
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: app_identifier,
      ipa: options.fetch(:ipa),
      distribute_external: false,
      skip_waiting_for_build_processing: false,
      wait_processing_timeout_duration: 3600
    )
  end
end
