export type UnitGroup =
  | 'epic-hero'
  | 'character'
  | 'battleline'
  | 'infantry'
  | 'swarm'
  | 'mounted'
  | 'beast'
  | 'monster'
  | 'vehicle'
  | 'drone'
  | 'transport'
  | 'fortification'
  | 'other'
